steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  — functions
  — deploy
  — — runtime=python39
  — — trigger-http
  — — source=app/. # Function source files
  — — entry-point=get_tweets_ikea # Function entry point
  — get_tweets_ikea # Function name
  waitFor: ['push-image-to-container-registry']
  id: 'deploying-a-serverless-function'

