steps:
- name: 'python'
  args: ['pip3','install', '-r', 'requirements.txt', '--user']
# Create a task for each function as shown here: https://cloud.google.com/functions/docs/bestpractices/testing#continuous_testing_and_deployment
- name: 'gcr.io/cloud-builders/gcloud']
    id: 'deployMyFunction'
  args: ['functions', 'deploy', 'my-function', '--source' , 'app/ikea_tweets_api.py', '--runtime' , 'python37' ,'--trigger-http']
images:
- 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'
- 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$BUILD_ID'
